server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: QwEr3466
    url: jdbc:postgresql://localhost:5432/search_engine
#    url: jdbc:postgresql://62.148.227.113:5432/search_engine
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: update
    show-sql: false
#    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru