server:
  port: 8080

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: ERROR
spring:
  datasource:
    username: postgres
    password: QwEr3466
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
  #    test-while-idle: true
  #    validation-query: SELECT 1;
  #    time-between-eviction-runs-millis: 60000
  #    remove-abandoned: true
  #    remove-abandoned-timeout: 60
  #    hikari:
  #      idle-timeout: 600000
  #      validationTimeout: 300000
  #      connectionTimeout: 30000
  #      idleTimeout: 600000
  #      maxLifetime: 1800000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
  #    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

indexing-settings:
  sites:
    #    - url: https://lenta.ru
    #      name: Лента.ру
    #    - url: https://skillbox.ru
    #      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: http://radiomv.ru
#      name: MiliceyskayaVolna