package searchengine.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;


@Entity
@Getter
@Setter
@ApiModel(description = "entity representing search indexes")
@Table(name = "Indexes", indexes = {@Index(name = "page_id", columnList = "page_id"),
        @Index(name = "lemma_id", columnList = "lemma_id")})
public class IndexEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private int id;

    @Column(columnDefinition = "FLOAT NOT NULL")
    @ApiModelProperty("rank of lemma")
    private float rank;

    @ManyToOne
    @JoinColumn(name = "page_id", referencedColumnName = "id", nullable = false)
    @JsonIgnore
    private PageEntity page;

    @ManyToOne
    @JoinColumn(name = "lemma_id", referencedColumnName = "id", nullable = false)
    @JsonIgnore
    private LemmaEntity lemma;

    public IndexEntity(float rank, PageEntity page, LemmaEntity lemma) {
        this.rank = rank;
        this.page = page;
        this.lemma = lemma;
    }

    public IndexEntity() {
        this(0f, null, null);
    }
}
