package searchengine.model;

import com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Type;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Set;

@Entity
@Getter
@Setter
@ApiModel(description = "entity representing a website")
@Table(name = "sites")
public class SiteEntity implements Serializable {

    @Id
    @ApiModelProperty("id generated by db automatically")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    @ApiModelProperty("indexing status")
    @Enumerated(EnumType.STRING)
    @Type(PostgreSQLEnumType.class)
    @Column(name = "status", columnDefinition = "status_type", nullable = false)
    private StatusType status;

    @Column(name = "status_time", nullable = false)
    @ApiModelProperty("time when status was changed")
    private LocalDateTime statusTime;

    @Column(name = "last_error", columnDefinition = "TEXT")
    @ApiModelProperty("description of last error")
    private String lastError;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("URL of website")
    private String url;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("name of website")
    private String name;

    @OneToMany(mappedBy = "site", cascade = CascadeType.ALL)
//    @LazyCollection(LazyCollectionOption.EXTRA)
    private Set<PageEntity> pageEntities;

    @OneToMany(mappedBy = "site", cascade = CascadeType.ALL)
//    @LazyCollection(LazyCollectionOption.EXTRA)
    private Set<LemmaEntity> lemmaEntities;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SiteEntity that = (SiteEntity) o;

        if (id != that.getId()) return false;
        if (!Objects.equals(status, that.status)) return false;
        if (!Objects.equals(statusTime, that.statusTime)) return false;
        if (!Objects.equals(lastError, that.lastError)) return false;
        if (!Objects.equals(url, that.url)) return false;
        return Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (status != null ? status.hashCode() : 0);
        result = 31 * result + (statusTime != null ? statusTime.hashCode() : 0);
        result = 31 * result + (lastError != null ? lastError.hashCode() : 0);
        result = 31 * result + (url != null ? url.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}
