package searchengine.model.site;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import searchengine.model.StatusType;
import searchengine.model.page.PageEntity;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Getter
@Setter
@ApiModel(description = "entity representing a website")
@Table(name = "sites")
public class SiteEntity implements Serializable {

    @Id
    @ApiModelProperty("id generated by db automatically")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(columnDefinition = "enum('INDEXING', 'INDEXED', 'FAILED') NOT NULL")
    @ApiModelProperty("indexing status")
    @Enumerated(EnumType.STRING)
    private StatusType status;

    @Column(name = "status_time", columnDefinition = "DATETIME NOT NULL")
    @ApiModelProperty("time when status was changed")
    private LocalDateTime statusTime;

    @Column(name = "last_error", columnDefinition = "TEXT")
    @ApiModelProperty("description of last error")
    private String lastError;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("URL of website")
    private String url;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("name of website")
    private String name;

    @OneToMany(mappedBy = "site", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Set<PageEntity> pageEntities = new HashSet<>();
}
