package searchengine.model.site;

import com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import searchengine.services.StatusType;
import searchengine.model.page.PageEntity;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Getter
@Setter
@ApiModel(description = "entity representing a website")
@Table(name = "sites")
@TypeDef(
        name = "status_type",
        typeClass = PostgreSQLEnumType.class
)
public class SiteEntity implements Serializable {

    @Id
    @ApiModelProperty("id generated by db automatically")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ApiModelProperty("indexing status")
    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    @Type( type = "status_type" )
    private StatusType status;

    @Column(name = "status_time", nullable = false)
    @ApiModelProperty("time when status was changed")
    private LocalDateTime statusTime;

    @Column(name = "last_error", columnDefinition = "TEXT")
    @ApiModelProperty("description of last error")
    private String lastError;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("URL of website")
    private String url;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("name of website")
    private String name;

    @OneToMany(mappedBy = "site", cascade = CascadeType.ALL)
    private Set<PageEntity> pageEntities = new HashSet<>();
}
