package searchengine.model.lemma;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import searchengine.model.site.SiteEntity;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Getter
@Setter
@ApiModel(description = "entity representing lemmas")
@Table(name = "lemmas")
public class Lemma implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private long id;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "site_id", referencedColumnName = "id")
    @JsonIgnore
    private SiteEntity siteEntity;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("normal form of a word")
    private String lemma;

    @Column(columnDefinition = "INT NOT NULL")
    @ApiModelProperty("the number of pages where the word occurs at least once")
    private int frequency;

    @OneToOne(mappedBy = "lemma")
    private searchengine.model.index.Index index;
}
